### ISSUE TITLE
What is the unit of latitude and longitude in the /gnss/pose.txt file?

### ISSUE THREAD

**Issue by bryantaoli** [RoboticsBUT/Brno-Urban-Dataset#2]
After downloading the data, I found that the latitude and longitude values in the pose.txt file under the gnss folder of 1_1_1_6 have changed greatly. What is the unit of latitude and longitude in the /gnss/pose.txt file?

**Comment by RoboticsBUT** [comment]
Hi, thanks for your message. The latitude and longitude units are degrees in the WGS84 reference system. However there is no 1_1_1_6 record session. Did you mean 1_1_6_1?

**Comment by bryantaoli** [comment]
Yes, I am sorry that I make a mistake, it is 1_1_6_1.

**Comment by RoboticsBUT** [comment]
Yep, so I have found no big changes in the second and the third columns (these are latitude and logitude). The significant change in in the fourth column at 1818th row, which is altitude. This number gives meters above the see. And yes altitude and heading (fifth column) could be more noisy, but latitude and longitude should be precise.

**Comment by bryantaoli** [comment]
Yes, I found it precise, thank you, and I raised an issue in another repository of you, which is https://github.com/Robotics-BUT/Brno-Urban-Dataset-Tools/issues/2 , can you help me to fix the bug

**Comment by bryantaoli** [comment]
And what do you mean "All rotations and translations are the fransformations from the center of the sensory framework into the specific sensor frame." which is in the file /calibrations/frames.yaml.  For example lidar_left:
    trans: [0.17, 0.48, 0.15]
    rot:   [0.0012719, -0.0632113, -0.9977974, 0.0200754] is the rotations and translations from lidar_left to IMU or from IMU to lidar_left？

**Comment by RoboticsBUT** [comment]
All the transformations and rotations are right-handed and the IMU is the reference. That is mean that translation [0.17, 0.48, 0.15] meand 17cm forward, 48cm left and 15cm up w.r.t. IMU sensor. Rotation is also right-handed, for more informations please see ROS transformation documentation.

**Comment by bryantaoli** [comment]
So the IMU sensor's X axis is IMU's forward, the IMU sensor's Y axis is IMU's left,  the IMU sensor's Z axis is IMU's up?
And if I make the trans  [0.17, 0.48, 0.15] and rot: [0.0012719, -0.0632113, -0.9977974, 0.0200754] as matric Tlidar_imu, does it mean that the Plidar=Tlidar_imu*Pimu？

**Comment by RoboticsBUT** [comment]
Exactly

**Comment by bryantaoli** [comment]
> Exactly

OK, thank you so much, and I raised an issue in another repository of you, which is Robotics-BUT/Brno-Urban-Dataset-Tools#2 , can you help me to fix the bug
