### ISSUE TITLE
Cannot download data now

### ISSUE THREAD

**Issue by hitdshu** [RoboticsBUT/Brno-Urban-Dataset#3]
Hi,

Thanks for your sharing of your data. 

I downloaded the torrent file. However, the corresponding true files might not be downloadable from its torrent file, as the download speed is const zero...

So could you please check the effectiveness of the torrent files...

Thanks very much.

Deshun

**Comment by adamek727** [comment]
Hi, thanks for your note. We have some difficulties with torrent tracker. Working on it. As soon as we will fix it, I will let you know.

**Comment by adamek727** [comment]
Ok, so the problem should be fixed. Please let mi now if the torrents work.

**Comment by hitdshu** [comment]
It works now. Thanks very much for your timely help.
