### ISSUE TITLE
Cannot download data now

### ISSUE THREAD

**Issue by NextNode66** [RoboticsBUT/Brno-Urban-Dataset#4]
Hi,
Thanks for your sharing of your datasets.
I am trying to use your datasets to do some research, but I can't download your datasets through torrent files. could you please check the effectiveness of the torrent files or provide some other download methods?
Thank you!

**Comment by adamek727** [comment]
Hi sorry for late answer. Do you still have a problem? From my point of view all should be working. Even now, someone is downloading data.

**Comment by Elkulas** [comment]
> Hi sorry for late answer. Do you still have a problem? From my point of view all should be working. Even now, someone is downloading data.

Now its still not working for me 
![image](https://user-images.githubusercontent.com/27431999/147103709-e1d521fa-8e11-4975-8348-5c176ca583fd.png)

**Comment by jykim7808** [comment]
I also can't download the dataset. There seems to be no torrent seed.

**Comment by adamek727** [comment]
Sorry for late. We had difficulties with server stability. Not it should work. Somebody is currently downloading.

**Comment by Jibanul** [comment]
![Screenshot from 2022-03-24 13-58-31](https://user-images.githubusercontent.com/22851740/159980545-79a7799e-194c-46c2-973d-842f9946fda6.png)

It's been like this for hours. Any suggestion or any other source to download the data? Thanks!

**Comment by Cerf-Volant425** [comment]
I've also met the same problem, there seems to be no torrent seed...

**Comment by DreamWaterFound** [comment]
@adamek727 
Hi~ sorry to bother you, but I have the same problem. Information reported by `qBittorrent` shows that the service in tracker server may crashed:

![Screenshotq - qBittorrent](https://user-images.githubusercontent.com/33981288/163581252-da6fc970-4efe-4c4c-9675-eae284cdd9dd.png)

and, the tracker server can respond the ICMP packets:

![Screenshot2 - ping the tracker server](https://user-images.githubusercontent.com/33981288/163582166-330d4b7f-70a8-471b-835c-1fb18451f578.png)

I'm not quite sure how to solve this problem. Could you please check the working status of the server? Thank you so much for your help!

**Comment by Kailthen** [comment]
same problem

**Comment by adamek727** [comment]
Sorry for late answer. Actually the server machine is broken. I am currently out of office. I expect to fix it in a week or two. Sorry for complications.

**Comment by Kailthen** [comment]
> Sorry for late answer. Actually the server machine is broken. I am currently out of office. I expect to fix it in a week or two. Sorry for complications.

Thanks, i'm still interest in your dataset.

**Comment by DreamWaterFound** [comment]
> > Sorry for late answer. Actually the server machine is broken. I am currently out of office. I expect to fix it in a week or two. Sorry for complications.
> 
> Thanks, i'm still interest in your dataset.

+1

**Comment by Kailthen** [comment]
@adamek727 Sorry for bothering, is the data still available now ? 
![image](https://user-images.githubusercontent.com/46671312/182506366-1a06faf3-50e7-4f1d-a685-ba67009560b8.png)

**Comment by akashsonth** [comment]
Hi, is the data available yet?

**Comment by Haalum** [comment]
I gave up on this. I have spent weeks trying to download this data. Something wrong with the server. I suggest you move on with another data instead of fixating on this. Good Luck!

**Comment by WT834** [comment]
still no seeds?

**Comment by adamek727** [comment]
Sorry for complications. We have a long-term difficulties with server. Data should be back online in about 3 weeks.

**Comment by rem821** [comment]
@WT834 @akashsonth @Kailthen Can confirm the whole dataset is available again.

**Comment by DreamWaterFound** [comment]
> Sorry for late answer. Actually the server machine is broken. I am currently out of office. I expect to fix it in a week or two. Sorry for complications.

Seems still be unavailable ...

![Screenshot from 2022-12-04 15-10-20](https://user-images.githubusercontent.com/33981288/205478937-dd2ba513-3399-4338-bec9-47fbc9e8a822.png)
(Transmission)

![Screenshot from 2022-12-04 15-10-14](https://user-images.githubusercontent.com/33981288/205478947-0804b2bc-8ed3-41ec-a4a1-ce034b42b7c7.png)
(qBittorrent)

**Comment by rem821** [comment]
@DreamWaterFound Are you connected to the opentrackr tracker? Yesterday I've downloaded the first session (currently seeding) and downloading the second one today.

**Comment by DreamWaterFound** [comment]
@rem821 It looks like I have connected with `opentracker` and there are 2 peers and 1 seed, but I cannot download anything ?

![Screenshot from 2022-12-05 11-16-33](https://user-images.githubusercontent.com/33981288/205541936-9819791f-46b1-432c-ba7f-08f47a92b2cd.png)

Could you give me any tips? Thanks a lot

**Comment by rem821** [comment]
@DreamWaterFound I've created a client with public IP that has first and part of the second session available. This one won´t be running 24/7 for next couple of days (off during the night UTC+1), but I'll move to a different PC with public IP as soon as I download the whole dataset myself. 

In the mean time, if I'm not available, try to leave your client running overnight, I'll try to keep the availability high.

**Comment by DreamWaterFound** [comment]
@rem821 I will test following your tips in these days. Thank you very much for your help!

**Comment by rem821** [comment]
Few more updates on this issue:
1) I've moved the dataset to the server running 24/7 and public IP with an open port configured. 
2) Also I would suggest to anyone to use some of the more established torrent clients (like qBittorrent) as they have proper support for DHT which makes connecting quicker without relying on trackers.
3) I've also registered all torrent files to Academic Torrents so there are two trackers to choose from

**Comment by DreamWaterFound** [comment]
@rem821 I want to express the depth of my gratitude to you!

I have downloaded the sequence `1_1_1_1` successfully.

For the convenience of our community, I will make the resources seeding as far as I can.

**Comment by grdiv** [comment]
> Few more updates on this issue:
> 
> 1. I've moved the dataset to the server running 24/7 and public IP with an open port configured.
> 2. Also I would suggest to anyone to use some of the more established torrent clients (like qBittorrent) as they have proper support for DHT which makes connecting quicker without relying on trackers.
> 3. I've also registered all torrent files to Academic Torrents so there are two trackers to choose from

can you provide via google drive? Thanks!

**Comment by rem821** [comment]
@grdiv sadly we don't have a google drive plan that would allow for this right now. Our new server room is in the works so we'll be moving the dataset to allow for FTP connections. It is estimated to go online early 2023, but its out of our influence right now.

**Comment by grdiv** [comment]
> FTP connections

I got it, thanks for the reply. look forward to online FTP
